import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Hero } from "./sections/Hero";

const clash = localFont({
  src: "./ClashGrotesk-Variable.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${clash.className} antialiased`}>
        <main className={`${clash.className} antialiased`}>{children}</main>
      </body>
    </html>
  );
}
